name: sonda
description: Radar de dispositivos eletrônicos ao redor via Bluetooth LE.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
